development:
  adapter: postgresql
  encoding: unicode
  database: sanicyt_development
  pool: 2
  host: localhost
  username: sanicyt
  password: 12345678

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>